version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: decp_rabbitmq
    ports:
      - "5672:5672" # AMQP protocol port
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  # mongodb:
  #   image: mongo:latest
  #   container_name: decp_mongodb
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodb_data:/data/db

volumes:
  rabbitmq_data:
  # mongodb_data:
